# Generated by Django 3.1.7 on 2021-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(null=True),
        ),
    ]
