# Generated by Django 3.1.7 on 2021-03-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20210307_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
