# Generated by Django 3.1.7 on 2021-03-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_auto_20210307_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackTitle', models.CharField(default='new feedback', max_length=255)),
                ('feedbackDescription', models.TextField(default='feedback body')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedbacks', to='adminApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='AdminFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackTitle', models.CharField(max_length=255)),
                ('feedbackDescription', models.TextField(default='feedback body')),
                ('responseTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='adminApp.instructorfeedback')),
            ],
        ),
    ]
