# Generated by Django 3.1.7 on 2021-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_adminfeedback_instructorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorfeedback',
            name='has_response',
            field=models.BooleanField(default='False'),
        ),
    ]
