# Generated by Django 3.1.7 on 2021-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_instructorfeedback_has_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='media/profilePics'),
        ),
    ]
