# Generated by Django 3.1.7 on 2021-03-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certDate', models.DateField(auto_now_add=True)),
                ('certUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentValue', models.TextField()),
                ('contentImage', models.ImageField(upload_to='media/')),
                ('contentAudio', models.FileField(upload_to='media/')),
                ('contentVideo', models.FileField(upload_to='media/')),
                ('isComplete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseDescription', models.TextField()),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.content')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteLang', models.CharField(max_length=200)),
                ('startLevel', models.CharField(max_length=20)),
                ('currLevel', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('questionDir', models.FilePathField(path='../Questions')),
                ('answerDir', models.FilePathField(path='../Answers')),
                ('scored', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='language_app.certificate')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.course')),
                ('gradeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.grade')),
                ('prefId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.preference')),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='courseId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='language_app.course'),
        ),
    ]
