# Generated by Django 3.1.7 on 2021-03-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0002_student_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contents',
        ),
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='language_app.course'),
        ),
    ]
