# Generated by Django 3.1.7 on 2021-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0003_auto_20210307_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseImage',
            field=models.FileField(default='', max_length=255, upload_to='courseImages/'),
        ),
    ]
