# Generated by Django 3.1.7 on 2021-03-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_auto_20210307_1214'),
        ('language_app', '0005_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='adminApp.instructor'),
        ),
    ]
