# Generated by Django 3.1.7 on 2021-03-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0010_remove_course_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentAudio',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentImage',
            field=models.ImageField(max_length=500, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentVideo',
            field=models.FileField(max_length=50, upload_to='media/'),
        ),
    ]
