# Generated by Django 3.1.7 on 2021-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0011_auto_20210308_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentVideo',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
    ]
