# Generated by Django 3.1.7 on 2021-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0012_auto_20210308_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='isComplete',
            field=models.BooleanField(null=True),
        ),
    ]
