# Generated by Django 3.1.7 on 2021-03-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0014_course_courseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='isComplete',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='startLevel',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answerDir',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='scored',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gradeId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prefId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizId',
        ),
        migrations.AddField(
            model_name='certificate',
            name='userId',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certId', to='language_app.student'),
        ),
        migrations.AddField(
            model_name='content',
            name='contentLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='contentTitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='selfID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='userId',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gradeId', to='language_app.student'),
        ),
        migrations.AddField(
            model_name='preference',
            name='currContentId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prefId', to='language_app.content'),
        ),
        migrations.AddField(
            model_name='preference',
            name='userId',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prefId', to='language_app.student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isComplete', models.BooleanField(default=False)),
                ('contentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.content')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.student')),
            ],
            options={
                'unique_together': {('contentId', 'userId')},
            },
        ),
    ]
