# Generated by Django 3.1.7 on 2021-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0015_auto_20210319_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='media/profilePics'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questionDir',
            field=models.FilePathField(path='Questions/'),
        ),
    ]
