# Generated by Django 3.1.7 on 2021-03-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_auto_20210322_0900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language_app', '0016_auto_20210322_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isComplete', models.BooleanField(default=False)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseTakesId', to='language_app.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='currContentId',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='currLevel',
        ),
        migrations.AddField(
            model_name='content',
            name='courseId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='language_app.course'),
        ),
        migrations.AddField(
            model_name='content',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminApp.instructor'),
        ),
        migrations.AddField(
            model_name='content',
            name='userId',
            field=models.ManyToManyField(through='language_app.Takes', to='language_app.Student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.student'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='selfID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questionDir',
            field=models.FileField(upload_to='Questions/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profilePics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='takes',
            name='contentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takesContentId', to='language_app.content'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takesUserId', to='language_app.student'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currLevel', models.IntegerField(default=1)),
                ('currContentId', models.IntegerField(default=1)),
                ('courseTakesId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='statusCourseId', to='language_app.coursetakes')),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='statusUserId', to='language_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='coursetakes',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.student'),
        ),
    ]
