# Generated by Django 3.1.7 on 2021-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0017_auto_20210326_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizID',
            field=models.IntegerField(default=0),
        ),
    ]
