# Generated by Django 3.1.7 on 2021-03-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0018_quiz_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizID',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='userId',
        ),
        migrations.CreateModel(
            name='QuizTakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored', models.IntegerField(null=True)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiztakesId', to='language_app.quiz')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiztakesId', to='language_app.student')),
            ],
            options={
                'unique_together': {('quizId', 'userId')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='userId',
            field=models.ManyToManyField(through='language_app.QuizTakes', to='language_app.Student'),
        ),
    ]
